name: "IndexNow"
on:
  push:
    branches:

      # when git push to the main branch
      - main
  schedule:
    # scheduled in UTC.
    - cron:  '0 0,12 * * *'

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: submit-to-bing
        uses: bojieyang/indexnow-action@v1
        with:
          sitemap-location: "https://fuyuntechnology.github.io/sitemap.xml"  # 修改为你自己的
          endpoint: "www.bing.com"
          since: 1
          # minute, hour, day, week, month, year
          since-unit: "day"
          limit: 100
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: ${{ secrets.INDEXNOW_KEY_LOCATION }}
